modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "skill"
version = "${file.jarVersion}"
displayName = "Skill"
authors = "Yang, RitensekiP"
description = '''
Umacraft Skill Mod
'''

[[dependencies.skill]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skill]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
